### ISSUE TITLE
Create a bioconda package

### ISSUE THREAD

**Issue by mdehollander** [epruesse/SINA#1]
I have started to create a bioconda package, but even the binary version does not run on the conda images: https://github.com/bioconda/bioconda-recipes/pull/4099. Therefore we need to adjust the recipe to build from source: https://github.com/bioconda/bioconda-recipes/tree/master/recipes/sina. With @epruesse by email I discussed that to make a compiled package, first open motif and arb need to be added to conda.

**Comment by epruesse** [comment]
Requires various packages. See #8
