### ISSUE TITLE
Improve CSV output

### ISSUE THREAD

**Issue by v-kisand** [epruesse/SINA#10]
Hi Elmar,

Would be nice to be able to choose the information in taxonomy search output!

Thanx,
Veljo

**Comment by epruesse** [comment]
Can you be more specific about how you'd like this to work? I assume you refer to the way BLAST or vsearch allow you to specify the output columns?

**Comment by v-kisand** [comment]
yes, I mean something similar to the BLAST outfmt 6,7 and 10!

Thanks!
Veljo

2017-04-12 19:28 GMT+03:00 Elmar Pruesse <notifications@github.com>:
