### ISSUE TITLE
difficulties using SINA with my own MSA

### ISSUE THREAD

**Issue by korneel-emweb** [epruesse/SINA#110]
I'm trying to use SINA with an MSA I created, it's a reduced version of the SILVA database. As mentioned in the documentation I tried running `sina -i reference.fasta --prealigned -o reference.arb`. When I run SINA with this database I get some errors:
```
No HELIX filter found in ARB file. Disabling secondary structure features.
loadKey failed: sequence 'EU214627.1.1520' not found
...
```
The result still seems sort of correct ... I'm still wondering if this has any bad effect on the result? What is the HELIX filter that is missing? And in general, would you recommend using SINA with my own MSA?

**Comment by epruesse** [comment]
Yeah, the bug is in the error message. I'm getting it myself. It's on the fix list. You are correct, other than spamming your log with red error lines, it doesn't cause any trouble.

**Comment by korneel-emweb** [comment]
OK thanks for the reply! That's reassuring.
