### ISSUE TITLE
Allow adding sequence search result to output fasta

### ISSUE THREAD

**Issue by a1an77** [epruesse/SINA#19]
Hi, I would like to have an option to include the (aligned) homology search results into the output file. Ideally with an option to limit the number of sequences included. Would that be feasible?

**Comment by epruesse** [comment]
Hi Alan,

most definitely yes. 

It was actually possible at some point, but I seem to have dropped it. Probably because the code wasn't easy to maintain with all combinations of fasta and arb source and destination files.
