### ISSUE TITLE
SINA documentation

### ISSUE THREAD

**Issue by ZarulHanifah** [epruesse/SINA#20]
Hello Dr Pruesse,

Is it just me, or that the options in the online documentation didnt show up? And thank you so much for the software! (previously I simply used the online aligner, only recently I tried SINA cli)

**Comment by epruesse** [comment]
Yes, the documentation is in sore need of an update. I'm hoping to get a new version out some time soon, but haven't had the time to finish the work.

**Comment by epruesse** [comment]
The docs are now up to date and available at https://sina.readthedocs.io
