### ISSUE TITLE
Tab characters in sequence should be ignored

### ISSUE THREAD

**Issue by a1an77** [epruesse/SINA#21]
Tab characters are currently considered invalid and cause discard of the sequence containing them. They should be considered whitespace and ignored when processing the sequences instead.

**Comment by epruesse** [comment]
Agreed. Any chance for a PR?

**Comment by epruesse** [comment]
In case this is a blocker for you, you can convert the tabs to spaces like so (tr is really fast):
```
tr $'\t' ' ' <input.fasta >output.fasta
```

Or on the fly:
```
cat input.fasta | tr $'\t' ' '  | sina -i - [....]
```
