### ISSUE TITLE
activation of search leads to boost exception

### ISSUE THREAD

**Issue by Lagkouvardos** [epruesse/SINA#28]
When the --search flag is included an exception from boost is thrown. 

For example the command:
sina -i sequence.fasta -o sequence..aligned.fasta --db SILVA_132.arb --search-db SILVA_132.arb  --search

Will through:
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::bad_any_cast> >'
  what():  boost::bad_any_cast: failed conversion using boost::any_cast
Aborted (core dumped)

The command was run on Ubuntu 18.04 and 16.04 using conda installation or the precompiled distributions with the same results.

**Comment by epruesse** [comment]
Thanks!

Fixed in 1.3.5 :)
