### ISSUE TITLE
Search stage not parallelized

### ISSUE THREAD

**Issue by epruesse** [epruesse/SINA#32]
If the search DB and the reference DB are the same, and the engine is PT, the search should use the same PT servers. Otherwise it needs its own.

**Comment by KasperSkytte** [comment]
Hi!

Thank you for making SINA parallelizable in v1.4.0! Will this be fixed in the near future? 
Unfortunately, I mostly only use the search stage, so right now I have to brute force by splitting the input, run SINA in parallel processes using GNU parallel, and then combine. 

-Kasper

**Comment by epruesse** [comment]
I don't know yet. I'm working on an internal search engine hopefully obviating the need for the ARB PT server.

**Comment by KasperSkytte** [comment]
Alright, great. I imagine that would take some time. Thanks
