### ISSUE TITLE
Conda environment broken 

### ISSUE THREAD

**Issue by Roli-Wilhelm** [epruesse/SINA#50]
Hi, 

When I install via conda and run 'sina' I receive the following error:

sina: symbol lookup error: ~/anaconda3/envs/sina/bin/../lib/libsina.so.0: undefined symbol: _ZN5boost15program_options3argE

Thanks

**Comment by epruesse** [comment]
Can you post or attach the output of `conda list` from inside the env?

**Comment by Roli-Wilhelm** [comment]
# Name                    Version                   Build  Channel
arb-bio-tools             6.0.6                h5901010_5    bioconda
blas                      1.0                         mkl
boost                     1.67.0                   py37_4
bzip2                     1.0.6                h14c3975_5
ca-certificates           2018.03.07                    0
certifi                   2018.11.29               py37_0
gettext                   0.19.8.1             hd7bead4_3
glib                      2.56.2               hd408876_0
icu                       58.2                 h9c2bf20_1
intel-openmp              2019.1                      144
libarbdb                  6.0.6                h5901010_5    bioconda
libboost                  1.67.0               h46d08c1_4
libedit                   3.1.20170329         h6b74fdf_2
libffi                    3.2.1                hd88cf55_4
libgcc-ng                 8.2.0                hdf63c60_1
libgfortran-ng            7.3.0                hdf63c60_0
libstdcxx-ng              8.2.0                hdf63c60_1
mkl                       2019.1                      144
mkl_fft                   1.0.6            py37hd81dba3_0
mkl_random                1.0.2            py37hd81dba3_0
ncurses                   6.1                  he6710b0_1
numpy                     1.15.4           py37h7e9f1db_0
numpy-base                1.15.4           py37hde5b4d6_0
openssl                   1.1.1a               h7b6447c_0
pcre                      8.42                 h439df22_0
pip                       18.1                     py37_0
py-boost                  1.67.0           py37h04863e7_4
python                    3.7.1                h0371630_7
readline                  7.0                  h7b6447c_5
setuptools                40.6.3                   py37_0
sina                      1.4.0                h4ef8376_0    bioconda
sqlite                    3.26.0               h7b6447c_0
tbb                       2019.3               h2d50403_0    conda-forge
tk                        8.6.8                hbc83047_0
wheel                     0.32.3                   py37_0
xz                        5.2.4                h14c3975_4
zlib                      1.2.11               h7b6447c_3

**Comment by Roli-Wilhelm** [comment]
![image](https://user-images.githubusercontent.com/5546826/50180093-b554c800-02d6-11e9-95b1-4bbb00627100.png)

**Comment by epruesse** [comment]
Linux or OSX?

**Comment by epruesse** [comment]
Run 

```
conda install boost-cpp=1.67*
```

- hopefully that fixes it.

Somehow installing `python 3.7.1` leads to `libboost` being installed instead of `boost-cpp`, and that leads to the linker issue.

**Comment by Roli-Wilhelm** [comment]
Thanks for the speedy support; however, this did not fix the problem. The error remained even after I installed "boost-cpp-1.67.0" in the 'sina' conda environment.

**Comment by epruesse** [comment]
The underlying issue is that your environment has the boost libraries from defaults which are compiled with the new C++11 ABI while SINA was linked using the boost libraries from Conda forge which use the old ABI.

Can you double check your Channel List? It should have conda-forge > Bioconda > defaults.

You couldn’t try installing python 3.6 - maybe that’ll get the right libs in there.

As last resorts, install a fresh miniconda3, set the channels and try again. That should work.

Or use the binary tar balls from the release page. They have the right libs.

Elmar

--
message sent from mobile device

**Comment by santamanyu** [comment]
Hi, 

I am facing same error while running a binary script. Do you have any solutions for this?
Please find below the error log:
/Desktop/LCE_Automation/lce/bin$ ./lceproxy
./lceproxy: symbol lookup error: ./lceproxy: undefined symbol: _ZN5boost15program_options3argE


Thanks
Santamanyu
