### ISSUE TITLE
SINA in ARB_EDIT4 not working

### ISSUE THREAD

**Issue by mkorlevic** [epruesse/SINA#76]
I installed a precompiled SINA 1.6.0 on my computer and would like to use it within the ARB_EDIT4 sequence editor. After installing SINA the command to start SINA under Edit>SINA (SILVA Incremental Aligner) becomes available, but when I run it I get the following error in a bash terminal:

[famfinder] Option -ptdb deprecated; please use -db instead
Configuration error:
Reference database file ":" does not exist
Use "--help" to show options

Press RETURN to close Window

Kind regards,

Marino

**Comment by epruesse** [comment]
Thanks Marino! This is probably a problem in the command line parsing. I'll have a look at it as soon as I can.

**Comment by EmilRuff** [comment]
Hi Elmar,

I am having the same issue and get the same error (using SINA 1.6.0 and ARB 6.0.6).
If you want I can send you the console output.

Thanks and happy holidays,
Emil

**Comment by epruesse** [comment]
Fixed in `dev` - will be part of 1.6.1
