### ISSUE TITLE
SINA not running

### ISSUE THREAD

**Issue by tia-das** [epruesse/SINA#77]
I am running sina. every time the program gets killed at around 70%. i have changed % for ARB_MEMORY several times.
ARB_MEMORY=77% sina -i amplicons_seeds_uc.fasta --db SSURef_NR99_132_SILVA_13_12_17_opt.arb -o sina_out.fasta --outtype fasta --search --meta-fmt csv --lca-fields tax_slv --fs-engine internal --num-pts 8 -v --calc-idty --turn --search-min-sim 0.8

[2019-11-23 12:55:35.080] [log] [info] Loglevel set to info
12:55:35 [SINA] This is SINA 1.4.0.
12:55:35 [libARBDB] ARB: no FastLoad File 'SSURef_NR99_132_SILVA_13_12_17_opt.ARM' found => loading entire DB
12:55:43 [ARB I/O] Loading names map... (for "SSURef_NR99_132_SILVA_13_12_17_opt.arb")

0% 10 20 30 40 50 60 70 80 90 100%
|----|----|----|----|----|----|----|----|----|----|

12:55:44 [ARB I/O] Loading 695171 sequences...

0% 10 20 30 40 50 60 70 80 90 100%
|----|----|----|----|----|----|----|----|----|----|
************************************Killed

kindly help me to deduce the problem..

**Comment by epruesse** [comment]
As in the other tickets - try the 1.6.x first. How much memory do you have?
