### ISSUE TITLE
update SINA

### ISSUE THREAD

**Issue by tia-das** [epruesse/SINA#78]
In my Linux computer, SINA 1.4.0 is installed. i want to update it to SINA 1.5.0 so that i could run some code smoothly.
But i am unable to do that. i want to update it via bioconda..
kindly help me out.

Regards,
Tia Das,
JRF

**Comment by epruesse** [comment]
Hi @tia-das,

have a look at the Bioconda docs on how to get conda installed:

https://bioconda.github.io/user/install.html

Once you have a working bioconda installation, you can just `conda create -n sina sina` and then `conda activate sina` to have an environment with SINA installed inside it.

If you run into trouble, go to https://gitter.im/bioconda/Lobby and ask for help there. It's likely someone will be around to help you work through things.

(I'm going to close this as it's more of a bioconda issue than a SINA issue)
