### ISSUE TITLE
SINA not running. showing Gave up (Reason: ARB ERROR: Expected entry 'baseoff' is missing for species 'A6BReg23' and  Error during program execution: Failed to (re)build PT server index! (out of memory?)

### ISSUE THREAD

**Issue by tia-das** [epruesse/SINA#79]
i am trying to run SINA.
The code is as follows:
(my_env) pkd@pkd-HP-406-G1-MT:~/Desktop/Gargi/sequencing/another/Sina$ ARB_MEMORY=69% sina -i amplicons_seeds_uc.fasta --db SSURef_NR99_132_SILVA_13_12_17_opt.arb -o sina_out.fasta \ --search --meta-fmt csv --lca-fields tax_slv \ --fs-engine internal --num-pts 8 -v

The output is:
[2019-11-26 12:34:43.161] [log] [info] Loglevel set to info
12:34:43 [SINA] This is SINA 1.4.0.
12:34:43 [libARBDB] ARB: no FastLoad File 'SSURef_NR99_132_SILVA_13_12_17_opt.ARM' found => loading entire DB
12:34:52 [ARB I/O] Loading names map... (for "SSURef_NR99_132_SILVA_13_12_17_opt.arb")

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
12:34:53 [Search (ARB PT)] Using ARBHOME="/home/pkd/anaconda3/envs/my_env/lib/arb"
12:34:53 [Search (ARB PT)] PT server index out of date for SSURef_NR99_132_SILVA_13_12_17_opt.arb. Rebuilding:
ARB: Loading 'SSURef_NR99_132_SILVA_13_12_17_opt.arb.index.arb'
Warning: modification times of DB and fastload file differ (DB=1574751894 fastload=1574682344 diff=69550)
ARB: modification times of DB and fastload file differ (too much) => loading entire DB
ARB: Loading 'SSURef_NR99_132_SILVA_13_12_17_opt.arb.index.arb' done

Progress: Remove unused database entries
...................................................................... [  8.3%] left: 2m0s
...................................................................... [ 16.7%] left: 1m44s
...................................................................... [ 25.0%] left: 1m30s
...................................................................... [ 33.3%] left: 1m22s
...................................................................... [ 41.7%] left: 1m11s
...................................................................... [ 50.0%] left: 1m1s
...................................................................... [ 58.3%] left: 51s
...................................................................... [ 66.7%] left: 41s
...................................................................... [ 75.0%] left: 31s
...................................................................... [ 83.3%] left: 21s
...................................................................... [ 91.7%] left: 10s
...................................................................... [100.0%] used: 2m3s
[done]
Database contains 695171 species
Progress: Preparing sequence data
...................................................................... [  8.3%] left: 1m38s
...................................................................... [ 16.7%] left: 1m29s
...................................................................... [ 25.0%] left: 1m18s
...................................................................... [ 33.3%] left: 1m10s
...................................................................... [ 41.7%] left: 7m17s
...................................................................... [ 50.0%] left: 6m4s
...................................................................... [ 58.3%] left: 4m26s
...................................................................Killed
ARB: Loading 'SSURef_NR99_132_SILVA_13_12_17_opt.arb.index.arb'
Warning: modification times of DB and fastload file differ (DB=1574751894 fastload=1574682344 diff=69550)
ARB: modification times of DB and fastload file differ (too much) => loading entire DB
ARB: Loading 'SSURef_NR99_132_SILVA_13_12_17_opt.arb.index.arb' done

Building PT-Server for alignment 'ali_16s'...
Database contains 695171 species
Progress: Checking data
...................................................................... [100.0%] used: 0s
...................................................................... [200.0%] left: 0s
...................................................................... [300.0%] left: 0s
...................................................................... [400.0%] left: 0s
...................................................................... [500.0%] left: 0s
...................................................................... [600.0%] left: 0s
...................................................................... [700.0%] left: 0s
...................................................................... [800.0%] left: 0s
...................................................................... [900.0%] left: 0s
...................................................................... [1000.0%] left: 0s
...................................................................... [1100.0%] left: 0s
...................................................................... [1200.0%] left: 0s
[done]
Gave up (Reason: ARB ERROR: Expected entry 'baseoff' is missing for species 'A6BReg23')
Failed to write to '/home/pkd/anaconda3/envs/my_env/lib/arb/lib/pts/ptserver.log'
Failed to run 'arb_message 'Gave up (Reason: ARB ERROR: Expected entry "baseoff" is missing for species "A6BReg23")' &'
/home/pkd/anaconda3/envs/my_env/lib/arb/bin/arb_pt_server: Error: Gave up (Reason: ARB ERROR: Expected entry 'baseoff' is missing for species 'A6BReg23')
sum of above:  0 b
overall alloc: 0 b
sum of above:  0 b
overall alloc: 0 b
13:07:22 [FASTA I/O] read -1 sequences from -1 lines
13:07:22 [SINA] Error during program execution: Failed to (re)build PT server index! (out of memory?)
13:07:23 [ARB I/O] Closing ARB database '"SSURef_NR99_132_SILVA_13_12_17_opt.arb"'

Thus, Sina is not running successfully. Kindly help me...

**Comment by epruesse** [comment]
Hi @tia-das - I won't have time to do fixes for 1.4.0 - try using the 1.6.x please.

This looks to be some issue with your ARB database though. Try re-downloading the SILVA database you are using, perhaps it got corrupted somehow.
