### ISSUE TITLE
SINA alternatives

### ISSUE THREAD

**Issue by ayixon** [epruesse/SINA#83]
How good is SINA for small scale alignments (10-50 sequences)? Is it advisable to use SINA if I just want to align  less than 50 sequences to infer 16S phylogeny? Is it a suitable alternative to MUSCLE or MAFTT?

**Comment by epruesse** [comment]
Hi @ayixon!

SINA is very good at that. The algorithm aligns your query sequences to match the alignment in a pre-existing reference alignment such as the SILVA one. SINA can also copy related sequences from the reference alignment into the output, fleshing out the alignment for a better phylogenetic tree and giving you some meaningful anchors.

Here are some examples:

```bash
# just align
sina -i my_sequences.fasta -r silva_ssu_nr.arb -o my_sequences_aligned.fasta 

# align and add the closest k-mer match for each query to the output
sina -i my_sequences.fasta -r silva_ssu_nr.arb -o my_sequences_aligned.fasta \
     --add-relatives 1

# align and add the closest search result to the output
sina -i my_sequences.fasta -r silva_ssu_nr.arb -o my_sequences_aligned.fasta \
     --add-relatives 1 --search

# align and add the closest match from LTP to the output
sina -i my_sequences.fasta -r silva_ssu_nr.arb -o my_sequences_aligned.fasta \
     --add-relatives 1 --search --search-db LTP.arb
```

You could also head over to https://www.arb-silva.de/aligner/ and use the online tool, which will align the sequences, add some references and can even build a tree for you right away.
