### ISSUE TITLE
Disable progress bars

### ISSUE THREAD

**Issue by nr0cinu** [epruesse/SINA#85]
Hi!

Is it possible to disable the progress bars? This would be convenient, as their output fills up our log files with unnecessary information. If I use `--quiet`, there are still progress bars (e.g., for "Building Index").

Keep up the great work! :)

Thanks!

Best,
Bela

**Comment by epruesse** [comment]
Strange. They should actually turn off on their own when the output is not an interactive terminal. I’ll look into it. 

Elmar

--
message sent from mobile device

**Comment by epruesse** [comment]
Found the problem

**Comment by epruesse** [comment]
quick fix: 
 - add `--log-file sina.log` to create a log file without the spam
 - add  `&> /dev/null`  to silence sina terminal output completely

**Comment by nr0cinu** [comment]
Hi Elmar!

Excellent, thank you! I’ll try it out!

Best,
Bela

**Comment by epruesse** [comment]
Ok, #86 fixes your problem, plus another one or two.
