### ISSUE TITLE
SINA not processing fasta files that have been filtered using vsearch

### ISSUE THREAD

**Issue by dpar21** [epruesse/SINA#89]
I am trying to use SINA to align and classify 96 fastq files obtained from here: https://www.ebi.ac.uk/ena/data/view/PRJEB11512. I am really confused on how to use SINA to process these files, as whenever I process them it states that 0 sequences have been processed, kills the job, and my output files are all empty: 

![Screen Shot 2020-04-15 at 2 01 38 PM](https://user-images.githubusercontent.com/37747637/79370998-a0fffa00-7f21-11ea-9f1b-9e6c5e80a235.png)

I am also using 20 GB of memory, not sure if that is an issue. I believe it is with the fasta file itself (see below for first 2 sequences):

![Screen Shot 2020-04-15 at 2 04 19 PM](https://user-images.githubusercontent.com/37747637/79371218-018f3700-7f22-11ea-8d59-e6b7d09ffc46.png)

**Comment by dpar21** [comment]
Nevermind, I believe I may have figured out the issue: my fasta file was not in the correct order in terms of sequences (i.e. it should start from sequence 1 and then ascend)

**Comment by epruesse** [comment]
Sorry - I was too busy the last weeks :(

Happy to see that you worked it out youself! :)
