### ISSUE TITLE
Sina does not actually output LCA classification  anymore?

### ISSUE THREAD

**Issue by jvollme** [epruesse/SINA#91]
When using the old sina version downloadable from the SILVA website (1.2.11), it is possible to do LCA classification of the sequences with the --search argument. The classification is simply listed in the stderr-output of the run and has to be parsed from it, but it is there.

When using the new version with equivalent arguments, i do not get any classification results. only alignments. Currently i am often more interested in the LCA classification than the alignments.

Where/How do I find the LCA classification results?

**Comment by hmontenegro** [comment]
If you use the arguments `--meta-fmt csv --lca-fields tax_slv`, the LCA classification will be one of the columns from the csv file.

edit: I am not involved in the development of SINA in any way.

**Comment by epruesse** [comment]
The newest version can also just do `-o result.csv`, with `-f` specifying which fields.

**Comment by epruesse** [comment]
Please try the 1.7.0 - binaries should be ready within the hour and bioconda packages within the day.
