### ISSUE TITLE
How could I calculate identity between two 16S rDNA sequence？

### ISSUE THREAD

**Issue by fujch7** [epruesse/SINA#95]
Hi developer,

Thanks for the amazing tool. How could I calculate identity between two 16S rDNA sequence using sina？Just like Pablo Yarza described in his article https://www.nature.com/articles/nrmicro3330

Many thanks

**Comment by epruesse** [comment]
Hi @fujch7 - while I don't know how Pablo did the identity calculations, I know he was working with ARB. He probably used the distance matrix methods within it. Perhaps it's easiest to contact him directly via his Ribocon email address?

SINA has a number of options how the "fractional identity" can be computed. One of them should get you the same numbers. If not, do open another issue, I might be able to add that.
